@startuml (id=component)

    component "Auth service" as AuthService <<service>>

@enduml



@startuml (id=interfaces)

skinparam linetype polyline

!include auth-service.puml

' OAuth 2.0 & OpenID connect API
!startsub getAuthorize

    interface "GET  /authorize" as getAuthorize 
    AuthService --() getAuthorize

!endsub

!startsub postToken

    interface "POST /token" as postToken
    AuthService --() postToken

!endsub

!startsub postIntrospect

    interface "POST /introspect" as postIntrospect
    AuthService --() postIntrospect

!endsub

!startsub getUserinfo

    interface "GET  /userinfo" as getUserinfo
    AuthService --() getUserinfo

!endsub

!startsub getLogout

    interface "GET  /logout" as getLogout
    AuthService --() getLogout

!endsub

!startsub postRevoke

    interface "POST /revoke" as postRevoke
    AuthService --() postRevoke

!endsub

' Internal use API
!startsub getCheckOTP

    interface "GET /checkOTP" as getCheckOTP
    AuthService --() getCheckOTP

!endsub

!startsub getCheckLogin

    interface "GET /checkLogin" as getCheckLogin
    AuthService --() getCheckLogin

!endsub

@enduml



@startuml (id=idp)

skinparam linetype polyline

!include auth-service.puml
!includesub auth-service.puml!getAuthorize
!includesub auth-service.puml!postToken
!includesub auth-service.puml!postIntrospect
!includesub auth-service.puml!getUserinfo
!includesub auth-service.puml!postRevoke
!includesub auth-service.puml!postMfaChallenge

@enduml



@startuml (id=custom)

skinparam linetype polyline

!include auth-service.puml
!includesub auth-service.puml!getCheckOTP
!includesub auth-service.puml!getCheckLogin

@enduml