@startuml (id=component)

    component "Customer service" as CustomerService <<service>>

@enduml


@startuml (id=interfaces)

!startsub getCustomers

    interface "GET /customers" as getCustomers
    CustomerService --() getCustomers

!endsub

@enduml