@startuml (id=component)

component "1C DirectBank API Gateway" as 1CDirect <<service>>

@enduml

@startuml (id=interfaces)

!include 1c-directbank-gateway.puml

!startsub getSettings

    interface "POST /GetSettings" as getSettings
    1CDirect --() getSettings

!endsub

!startsub logonCert

    interface "POST /LogonCert" as logonCert
    1CDirect --() logonCert

!endsub

!startsub logonOTP

    interface "POST /LogonOTP" as logonOTP
    1CDirect --() logonOTP

!endsub

!startsub logon

    interface "POST /Logon" as logon
    1CDirect --() logon

!endsub

@enduml