@startuml (id=component)

component "CryptoPro Certificate Authority" as CryptoProCA <<Bank system>> #IndianRed

@enduml



@startuml (id=provide-interfaces)

!include ./cryptopro-ca.puml

!startsub getCertificateRecordList
    
    interface "POST /GetCertificateRecordList" as getCertificateRecordList
    CryptoProCA --() getCertificateRecordList

!endsub

@enduml