@startuml components-library

left to right direction

frame "Payment management" {
    component "Payment services" as Payment <<service>>
    component "Fast payment services" as FastPayment <<service>>
    component "Document number services" as DocumentNumber <<Component>>
    component "Cash withdrawal services" as CashWithdrawal <<Component>>
    component "QR services" as QR <<Component>>
    component "Counterparty services" as Counterparty <<Component>>
    component "Limit counter services" as LimitCounter <<Component>>
    component "Mobile operator detects services" as MobileOperatorDetects <<Component>>
    component "Meter services" as Meter <<Component>>
}

frame "Account management" {
    component "Account services" as Account <<Component>>
}

frame "Deposit management" {
    component "Deposit services" as Deposit <<Component>>
}

frame "Card management" {
    [1]
}

frame "Loan management" {
    [2]
}

frame "Customer management" {
    [3]
}

frame "User management" {

}

frame "Offering management" {

}

frame "Risk management" {

}

frame "PKI management" {

}

frame "Acquiring management" {

}

frame "Support management" {

}

frame "Generic services" {

}

frame "Tax management" {

}


'Technical layer

frame "Clients" {

}

frame "Infrastructure" {

}

frame "Integration" {

}

@enduml